language: scala

scala:
  - 2.13.1

jdk:
  - openjdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt clean
  - sbt prep # Check pre-push style hook in order to avoid `push --no-verify` h4ck3rs
  # Execute the tests including code coverage. More info: https://github.com/scoverage/sbt-coveralls
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M coverage test